const napiEsemenyek = {
    "01-01": ["Újév", "Fruzsina napja"],
    "01-02": ["Ábel napja"],
    "01-03": ["Genovéva napja"],
    "01-04": ["Titusz napja", "Braille-írás világnapja"],
    "01-05": ["Simon napja"],
    "01-06": ["Vízkereszt", "Boldizsár napja"],
    "01-07": ["Attila napja"],
    "01-08": ["Gyöngyvér napja"],
    "01-09": ["Marcell napja"],
    "01-10": ["Melánia napja"],
    "01-11": ["Ágota napja"],
    "01-12": ["Ernő napja"],
    "01-13": ["Veronika napja"],
    "01-14": ["Bódog napja"],
    "01-15": ["Lóránt napja"],
    "01-16": ["Gusztáv napja"],
    "01-17": ["Antal napja"],
    "01-18": ["Piroska napja", "A magyar vallásszabadság napja"],
    "01-19": ["Sára napja"],
    "01-20": ["Fábián és Sebestyén napja"],
    "01-21": ["Ágnes napja", "Az ölelés világnapja"],
    "01-22": ["Vince napja", "A magyar kultúra napja"],
    "01-23": ["Zelma napja"],
    "01-24": ["Timót napja"],
    "01-25": ["Pál napja"],
    "01-26": ["Vanda napja"],
    "01-27": ["Angyalka napja"],
    "01-28": ["Károly napja"],
    "01-29": ["Adél napja"],
    "01-30": ["Martina napja"],
    "01-31": ["Marcella napja"],
    "02-01": ["Ignác napja", "A Tisza emléknapja"],
    "02-02": ["Gyertyaszentelő Boldogasszony", "A szerzetesek világnapja"],
    "02-03": ["Balázs napja"],
    "02-04": ["Ráhel napja", "Rákellenes világnap"],
    "02-05": ["Ágota napja"],
    "02-06": ["Dorottya napja"],
    "02-07": ["Tódor napja"],
    "02-08": ["Aranka napja"],
    "02-09": ["Abigél napja"],
    "02-10": ["Elvira napja"],
    "02-11": ["Bertold napja", "A betegek világnapja"],
    "02-12": ["Lívia napja"],
    "02-13": ["Ella napja", "A rádió világnapja"],
    "02-14": ["Bálint napja (Valentin-nap)"],
    "02-15": ["Georgina napja"],
    "02-16": ["Julianna napja"],
    "02-17": ["Donát napja"],
    "02-18": ["Bernadett napja"],
    "02-19": ["Zsuzsanna napja", "A magyar ápolók napja"],
    "02-20": ["Aladár napja"],
    "02-21": ["Eleonóra napja", "Az anyanyelv nemzetközi napja"],
    "02-22": ["Gerzson napja", "A bűncselekmények áldozatainak napja"],
    "02-23": ["Alfréd napja"],
    "02-24": ["Mátyás napja"],
    "02-25": ["Géza napja", "A kommunista diktatúrák áldozatainak emléknapja"],
    "02-26": ["Viktor napja"],
    "02-27": ["Ákos napja"],
    "02-28": ["Elemér napja"],
    "02-29": ["Szökőnap (Hivatalosan ekkor tartják a ritka betegségek napját)"],
    "03-01": ["Albin napja", "Polgári védelem világnapja"],
    "03-02": ["Lujza napja"],
    "03-03": ["Kornélia napja", "Vadvilág világnapja"],
    "03-04": ["Kázmér napja"],
    "03-05": ["Adorján napja"],
    "03-06": ["Leonóra napja", "Energiatakarékossági világnap"],
    "03-07": ["Tamás napja"],
    "03-08": ["Zoltán napja", "Nemzetközi nőnap"],
    "03-09": ["Franciska napja"],
    "03-10": ["Ildikó napja"],
    "03-11": ["Szilárd napja"],
    "03-12": ["Gergely napja"],
    "03-13": ["Krisztián napja"],
    "03-14": ["Matild napja", "A nemzetközi π (Pi) nap"],
    "03-15": ["Nemzeti ünnep", "Kristóf napja"],
    "03-16": ["Henrietta napja"],
    "03-17": ["Gertrúd napja", "Szent Patrik napja"],
    "03-18": ["Sándor napja"],
    "03-19": ["József napja"],
    "03-20": ["Klaudia napja", "A boldogság nemzetközi napja"],
    "03-21": ["Benedek napja", "A költészet világnapja"],
    "03-22": ["Beáta napja", "A víz világnapja"],
    "03-23": ["Emőke napja", "A magyar–lengyel barátság napja"],
    "03-24": ["Gábor napja"],
    "03-25": ["Irén napja"],
    "03-26": ["Emánuel napja"],
    "03-27": ["Hajnalka napja", "A színházi világnap"],
    "03-28": ["Gedeon napja"],
    "03-29": ["Auguszta napja"],
    "03-30": ["Zalán napja"],
    "03-31": ["Árpád napja"],
    "04-01": ["Hugó napja", "Bolondok napja"],
    "04-02": ["Áron napja", "Az autizmus világnapja"],
    "04-03": ["Buda napja"],
    "04-04": ["Izidor napja"],
    "04-05": ["Vince napja"],
    "04-06": ["Vilmos napja"],
    "04-07": ["Herman napja", "Egészségügyi világnap"],
    "04-08": ["Dénes napja", "A romák világnapja"],
    "04-09": ["Ervin napja"],
    "04-10": ["Zsolt napja"],
"04-11": ["Leó napja", "A magyar költészet napja"],
    "04-12": ["Gyula napja", "Az űrhajózás világnapja"],
    "04-13": ["Ida napja"],
    "04-14": ["Tibor napja"],
    "04-15": ["Anasztázia napja", "A művészet világnapja"],
    "04-16": ["Csongor napja", "A holokauszt magyarországi áldozatainak emléknapja"],
    "04-17": ["Rudolf napja"],
    "04-18": ["Andrea napja", "Műemlékvédelmi világnap"],
    "04-19": ["Emma napja"],
    "04-20": ["Tivadar napja"],
    "04-21": ["Konrád napja"],
    "04-22": ["Csilla napja", "A Föld napja"],
    "04-23": ["Béla napja", "A könyv világnapja"],
    "04-24": ["György napja", "A rendőrség napja"],
    "04-25": ["Márk napja"],
    "04-26": ["Ervin napja", "A szellemi tulajdon világnapja"],
    "04-27": ["Zita napja"],
    "04-28": ["Valéria napja"],
    "04-29": ["Péter napja", "A táncművészet világnapja"],
    "04-30": ["Katalin napja", "A magyar film napja"],
    "05-01": ["Munka ünnepe", "Fülöp és Jakab napja"],
    "05-02": ["Zsigmond napja"],
    "05-03": ["Tímea napja", "A sajtószabadság világnapja"],
    "05-04": ["Mónika napja", "Flórián napja (Tűzoltók napja)"],
    "05-05": ["Györgyi napja"],
    "05-06": ["Ivett napja", "A magyar sport napja"],
    "05-07": ["Gizella napja"],
    "05-08": ["Mihály napja", "A Vöröskereszt világnapja"],
    "05-09": ["Gergely napja", "Európa-nap"],
    "05-10": ["Ármin napja", "Mentők napja", "Madarak és fák napja"],
    "05-11": ["Ferenc napja"],
    "05-12": ["Pongrác napja", "Ápolók nemzetközi napja"],
    "05-13": ["Szervác napja"],
    "05-14": ["Bonifác napja"],
    "05-15": ["Zsófia napja", "A család nemzetközi napja"],
    "05-16": ["Botond napja"],
    "05-17": ["Paszkál napja", "A távközlés világnapja"],
    "05-18": ["Erik napja", "Múzeumi világnap"],
    "05-19": ["Ivó napja"],
    "05-20": ["Bernát napja", "A méhek világnapja"],
    "05-21": ["Konstantin napja", "A magyar honvédelem napja"],
    "05-22": ["Júlia napja", "A biológiai sokféleség világnapja"],
    "05-23": ["Dezső napja"],
    "05-24": ["Eszter napja", "Európai nemzeti parkok napja"],
    "05-25": ["Orbán napja"],
    "05-26": ["Fülöp napja"],
    "05-27": ["Hella napja"],
    "05-28": ["Emil napja"],
    "05-29": ["Magdolna napja"],
    "05-30": ["Janka napja"],
    "05-31": ["Angéla napja", "Dohányzásmentes világnap"],
    "06-01": ["Tünde napja"],
    "06-02": ["Kármen napja"],
    "06-03": ["Klothild napja"],
    "06-04": ["Bulcsú napja", "A nemzeti összetartozás napja"],
    "06-05": ["Fatime napja", "Környezetvédelmi világnap"],
    "06-06": ["Norbert napja"],
    "06-07": ["Róbert napja"],
    "06-08": ["Medárd napja", "Óceánok világnapja"],
    "06-09": ["Félix napja"],
    "06-10": ["Margit napja"],
    "06-11": ["Barnabás napja"],
    "06-12": ["Villő napja"],
    "06-13": ["Antal napja"],
    "06-14": ["Vazul napja", "Véradók világnapja"],
    "06-15": ["Jolán napja"],
    "06-16": ["Jusztin napja"],
    "06-17": ["Laura napja"],
    "06-18": ["Arnold napja"],
    "06-19": ["Gyárfás napja"],
    "06-20": ["Rafael napja", "Menekültek világnapja"],
    "06-21": ["Alajos napja", "A zene ünnepe"],
    "06-22": ["Paulina napja"],
    "06-23": ["Zoltán napja"],
    "06-24": ["János napja", "Szentivánéj"],
    "06-25": ["Vilmos napja"],
    "06-26": ["János napja", "Kábítószer-ellenes világnap"],
    "06-27": ["László napja"],
    "06-28": ["Levente napja"],
    "06-29": ["Péter és Pál napja"],
    "06-30": ["Pál napja"],
    "07-01": ["Tihamér napja", "Semmelweis-nap (Egészségügyi dolgozók napja)"],
    "07-02": ["Ottó napja"],
    "07-03": ["Kornél napja"],
    "07-04": ["Ulrik napja"],
    "07-05": ["Emese napja"],
    "07-06": ["Csaba napja"],
    "07-07": ["Apollónia napja"],
    "07-08": ["Ellák napja"],
    "07-09": ["Lukrécia napja"],
    "07-10": ["Amália napja"],
    "07-11": ["Nóra napja", "Népesedési világnap"],
    "07-12": ["Izabella napja"],
    "07-13": ["Jenő napja"],
    "07-14": ["Örs napja"],
    "07-15": ["Henrik napja"],
    "07-16": ["Valter napja"],
    "07-17": ["Endre napja"],
    "07-18": ["Frigyes napja"],
    "07-19": ["Emília napja"],
    "07-20": ["Illés napja"],
"04-11": ["Leó napja", "A magyar költészet napja"],
    "04-12": ["Gyula napja", "Az űrhajózás világnapja"],
    "04-13": ["Ida napja"],
    "04-14": ["Tibor napja"],
    "04-15": ["Anasztázia napja", "A művészet világnapja"],
    "04-16": ["Csongor napja", "A holokauszt magyarországi áldozatainak emléknapja"],
    "04-17": ["Rudolf napja"],
    "04-18": ["Andrea napja", "Műemlékvédelmi világnap"],
    "04-19": ["Emma napja"],
    "04-20": ["Tivadar napja"],
    "04-21": ["Konrád napja"],
    "04-22": ["Csilla napja", "A Föld napja"],
    "04-23": ["Béla napja", "A könyv világnapja"],
    "04-24": ["György napja", "A rendőrség napja"],
    "04-25": ["Márk napja"],
    "04-26": ["Ervin napja", "A szellemi tulajdon világnapja"],
    "04-27": ["Zita napja"],
    "04-28": ["Valéria napja"],
    "04-29": ["Péter napja", "A táncművészet világnapja"],
    "04-30": ["Katalin napja", "A magyar film napja"],
    "05-01": ["Munka ünnepe", "Fülöp és Jakab napja"],
    "05-02": ["Zsigmond napja"],
    "05-03": ["Tímea napja", "A sajtószabadság világnapja"],
    "05-04": ["Mónika napja", "Flórián napja (Tűzoltók napja)"],
    "05-05": ["Györgyi napja"],
    "05-06": ["Ivett napja", "A magyar sport napja"],
    "05-07": ["Gizella napja"],
    "05-08": ["Mihály napja", "A Vöröskereszt világnapja"],
    "05-09": ["Gergely napja", "Európa-nap"],
    "05-10": ["Ármin napja", "Mentők napja", "Madarak és fák napja"],
    "05-11": ["Ferenc napja"],
    "05-12": ["Pongrác napja", "Ápolók nemzetközi napja"],
    "05-13": ["Szervác napja"],
    "05-14": ["Bonifác napja"],
    "05-15": ["Zsófia napja", "A család nemzetközi napja"],
    "05-16": ["Botond napja"],
    "05-17": ["Paszkál napja", "A távközlés világnapja"],
    "05-18": ["Erik napja", "Múzeumi világnap"],
    "05-19": ["Ivó napja"],
    "05-20": ["Bernát napja", "A méhek világnapja"],
    "05-21": ["Konstantin napja", "A magyar honvédelem napja"],
    "05-22": ["Júlia napja", "A biológiai sokféleség világnapja"],
    "05-23": ["Dezső napja"],
    "05-24": ["Eszter napja", "Európai nemzeti parkok napja"],
    "05-25": ["Orbán napja"],
    "05-26": ["Fülöp napja"],
    "05-27": ["Hella napja"],
    "05-28": ["Emil napja"],
    "05-29": ["Magdolna napja"],
    "05-30": ["Janka napja"],
    "05-31": ["Angéla napja", "Dohányzásmentes világnap"],
    "06-01": ["Tünde napja"],
    "06-02": ["Kármen napja"],
    "06-03": ["Klothild napja"],
    "06-04": ["Bulcsú napja", "A nemzeti összetartozás napja"],
    "06-05": ["Fatime napja", "Környezetvédelmi világnap"],
    "06-06": ["Norbert napja"],
    "06-07": ["Róbert napja"],
    "06-08": ["Medárd napja", "Óceánok világnapja"],
    "06-09": ["Félix napja"],
    "06-10": ["Margit napja"],
    "06-11": ["Barnabás napja"],
    "06-12": ["Villő napja"],
    "06-13": ["Antal napja"],
    "06-14": ["Vazul napja", "Véradók világnapja"],
    "06-15": ["Jolán napja"],
    "06-16": ["Jusztin napja"],
    "06-17": ["Laura napja"],
    "06-18": ["Arnold napja"],
    "06-19": ["Gyárfás napja"],
    "06-20": ["Rafael napja", "Menekültek világnapja"],
    "06-21": ["Alajos napja", "A zene ünnepe"],
    "06-22": ["Paulina napja"],
    "06-23": ["Zoltán napja"],
    "06-24": ["János napja", "Szentivánéj"],
    "06-25": ["Vilmos napja"],
    "06-26": ["János napja", "Kábítószer-ellenes világnap"],
    "06-27": ["László napja"],
    "06-28": ["Levente napja"],
    "06-29": ["Péter és Pál napja"],
    "06-30": ["Pál napja"],
    "07-01": ["Tihamér napja", "Semmelweis-nap (Egészségügyi dolgozók napja)"],
    "07-02": ["Ottó napja"],
    "07-03": ["Kornél napja"],
    "07-04": ["Ulrik napja"],
    "07-05": ["Emese napja"],
    "07-06": ["Csaba napja"],
    "07-07": ["Apollónia napja"],
    "07-08": ["Ellák napja"],
    "07-09": ["Lukrécia napja"],
    "07-10": ["Amália napja"],
    "07-11": ["Nóra napja", "Népesedési világnap"],
    "07-12": ["Izabella napja"],
    "07-13": ["Jenő napja"],
    "07-14": ["Örs napja"],
    "07-15": ["Henrik napja"],
    "07-16": ["Valter napja"],
    "07-17": ["Endre napja"],
    "07-18": ["Frigyes napja"],
    "07-19": ["Emília napja"],
    "07-20": ["Illés napja"],
"10-21": ["Orsolya napja"],
    "10-22": ["Előd napja", "A dadogók nemzetközi világnapja"],
    "10-23": ["Nemzeti ünnep (1956-os forradalom)", "Gyöngyvér napja"],
    "10-24": ["Salamon napja", "Az ENSZ napja"],
    "10-25": ["Blanka napja"],
    "10-26": ["Dömötör napja"],
    "10-27": ["Szabina napja"],
    "10-28": ["Simon és Júdás napja"],
    "10-29": ["Nárcisz napja"],
    "10-30": ["Alfonz napja"],
    "10-31": ["Farkas napja", "A reformáció emléknapja", "Halloween"],
    "11-01": ["Mindenszentek", "Marianna napja"],
    "11-02": ["Halottak napja", "Achilles napja"],
    "11-03": ["Győző napja", "A magyar tudomány ünnepe"],
    "11-04": ["Károly napja", "Az emlékezés napja (az 1956-os forradalom leverése)"],
    "11-05": ["Imre napja"],
    "11-06": ["Lénárd napja"],
    "11-07": ["Rezső napja"],
    "11-08": ["Zsombor napja"],
    "11-09": ["Tivadar napja"],
    "11-10": ["Réka napja"],
    "11-11": ["Márton napja"],
    "11-12": ["Jónás és Renátó napja"],
    "11-13": ["Szilvia napja", "A magyar nyelv napja"],
    "11-14": ["Aliz napja", "A cukorbetegek világnapja"],
    "11-15": ["Albert napja"],
    "11-16": ["Ödön napja"],
    "11-17": ["Hortenzia napja", "Budapest napja"],
    "11-18": ["Jenő napja"],
    "11-19": ["Erzsébet napja"],
    "11-20": ["Jolán napja", "A gyermekek jogainak világnapja"],
    "11-21": ["Olivér napja", "A televíziózás világnapja"],
    "11-22": ["Cecília napja"],
    "11-23": ["Kelemen napja"],
    "11-24": ["Emma napja"],
    "11-25": ["Katalin napja"],
    "11-26": ["Virág napja"],
    "11-27": ["Virgil napja"],
    "11-28": ["Stefánia napja"],
    "11-29": ["Taksony napja"],
    "11-30": ["András napja"],
    "12-01": ["Elza napja", "Az AIDS elleni küzdelem világnapja"],
    "12-02": ["Melinda napja"],
    "12-03": ["Ferenc napja", "A fogyatékos emberek világnapja"],
    "12-04": ["Borbála napja"],
    "12-05": ["Vilma napja"],
    "12-06": ["Miklós napja (Mikulás)"],
    "12-07": ["Ambrus napja"],
    "12-08": ["Mária napja"],
    "12-09": ["Natália napja"],
    "12-10": ["Judit napja", "Az emberi jogok napja"],
    "12-11": ["Árpád napja"],
    "12-12": ["Gabriella napja"],
    "12-13": ["Luca napja"],
    "12-14": ["Szilárda napja", "A hűség napja"],
    "12-15": ["Valér napja"],
    "12-16": ["Etelka napja"],
    "12-17": ["Lázár napja"],
    "12-18": ["Auguszta napja", "A kisebbségek napja"],
    "12-19": ["Viola napja"],
    "12-20": ["Teofil napja"],
    "12-21": ["Tamás napja"],
    "12-22": ["Zénó napja"],
    "12-23": ["Viktória napja"],
    "12-24": ["Ádám és Éva napja", "Szenteste"],
    "12-25": ["Karácsony első napja", "Eugénia napja"],
    "12-26": ["Karácsony második napja", "István napja"],
    "12-27": ["János napja"],
    "12-28": ["Kamilla napja"],
    "12-29": ["Tamás napja"],
    "12-30": ["Dávid napja"],
    "12-31": ["Szilveszter napja"]
};